name = "cardano-foundation/cardano-blueprint-and-ecosystem-monitoring/escrow"
version = "0.1.0"
compiler = "v1.1.2"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'cardano-foundation/cardano-blueprint-and-ecosystem-monitoring/escrow'"

[repository]
user = "cardano-foundation/cardano-blueprint-and-ecosystem-monitoring"
project = "escrow"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2"
source = "github"

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.1.0-beta"
source = "github"

[config]
